apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aggregator
  namespace: {{ .Values.namespace }}
rules:
- apiGroups:
  - ioi.intel.com
  resources:
  - nodestaticioinfoes
  - nodeiostatuses
  - nodeiostatuses/status
  verbs:
  - get
  - update
  - list
  - watch
- apiGroups: 
  - ""
  resources:
  - configmaps
  - pods
  verbs:
  - get
  - watch
  - list
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - update
  - list
  - watch
  - create
  - patch
  - delete