/*
Copyright (C) 2025 Intel Corporation
SPDX-License-Identifier: Apache-2.0
*/

//
// aggregator.proto
//
// communicate with node agent
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.15.8
// source: pkg/api/aggregator/aggregator.proto

package aggregator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IOType int32

const (
	IOType_All         IOType = 0
	IOType_DiskIO      IOType = 1
	IOType_NetworkIO   IOType = 2
	IOType_RDT         IOType = 3
	IOType_RDTQuantity IOType = 4
)

// Enum value maps for IOType.
var (
	IOType_name = map[int32]string{
		0: "All",
		1: "DiskIO",
		2: "NetworkIO",
		3: "RDT",
		4: "RDTQuantity",
	}
	IOType_value = map[string]int32{
		"All":         0,
		"DiskIO":      1,
		"NetworkIO":   2,
		"RDT":         3,
		"RDTQuantity": 4,
	}
)

func (x IOType) Enum() *IOType {
	p := new(IOType)
	*p = x
	return p
}

func (x IOType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IOType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_aggregator_aggregator_proto_enumTypes[0].Descriptor()
}

func (IOType) Type() protoreflect.EnumType {
	return &file_pkg_api_aggregator_aggregator_proto_enumTypes[0]
}

func (x IOType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IOType.Descriptor instead.
func (IOType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_aggregator_aggregator_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_aggregator_aggregator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_aggregator_aggregator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pkg_api_aggregator_aggregator_proto_rawDescGZIP(), []int{0}
}

type UpdateNodeIOStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeName           string         `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	ObservedGeneration int64          `protobuf:"varint,2,opt,name=observed_generation,json=observedGeneration,proto3" json:"observed_generation,omitempty"`
	IoBw               []*IOBandwidth `protobuf:"bytes,3,rep,name=io_bw,json=ioBw,proto3" json:"io_bw,omitempty"`
}

func (x *UpdateNodeIOStatusRequest) Reset() {
	*x = UpdateNodeIOStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_aggregator_aggregator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateNodeIOStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNodeIOStatusRequest) ProtoMessage() {}

func (x *UpdateNodeIOStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_aggregator_aggregator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNodeIOStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateNodeIOStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_aggregator_aggregator_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateNodeIOStatusRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *UpdateNodeIOStatusRequest) GetObservedGeneration() int64 {
	if x != nil {
		return x.ObservedGeneration
	}
	return 0
}

func (x *UpdateNodeIOStatusRequest) GetIoBw() []*IOBandwidth {
	if x != nil {
		return x.IoBw
	}
	return nil
}

type IOBandwidth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// IO type: disk/network IO/rdt
	IoType IOType `protobuf:"varint,1,opt,name=io_type,json=ioType,proto3,enum=aggregator.IOType" json:"io_type,omitempty"`
	// key -> dev_id, value -> DeviceBandwidthInfo
	DeviceBwInfo map[string]*DeviceBandwidthInfo `protobuf:"bytes,2,rep,name=device_bw_info,json=deviceBwInfo,proto3" json:"device_bw_info,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *IOBandwidth) Reset() {
	*x = IOBandwidth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_aggregator_aggregator_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IOBandwidth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IOBandwidth) ProtoMessage() {}

func (x *IOBandwidth) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_aggregator_aggregator_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IOBandwidth.ProtoReflect.Descriptor instead.
func (*IOBandwidth) Descriptor() ([]byte, []int) {
	return file_pkg_api_aggregator_aggregator_proto_rawDescGZIP(), []int{2}
}

func (x *IOBandwidth) GetIoType() IOType {
	if x != nil {
		return x.IoType
	}
	return IOType_All
}

func (x *IOBandwidth) GetDeviceBwInfo() map[string]*DeviceBandwidthInfo {
	if x != nil {
		return x.DeviceBwInfo
	}
	return nil
}

type DeviceBandwidthInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Device's name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// key -> GA/BE/BT, Device's GA and BE pool status
	Status map[string]*IOStatus `protobuf:"bytes,2,rep,name=status,proto3" json:"status,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *DeviceBandwidthInfo) Reset() {
	*x = DeviceBandwidthInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_aggregator_aggregator_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceBandwidthInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceBandwidthInfo) ProtoMessage() {}

func (x *DeviceBandwidthInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_aggregator_aggregator_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceBandwidthInfo.ProtoReflect.Descriptor instead.
func (*DeviceBandwidthInfo) Descriptor() ([]byte, []int) {
	return file_pkg_api_aggregator_aggregator_proto_rawDescGZIP(), []int{3}
}

func (x *DeviceBandwidthInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeviceBandwidthInfo) GetStatus() map[string]*IOStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type IOStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Total IO bandwidth capacity in 32k blocksize, for disk IO
	Total float64 `protobuf:"fixed64,1,opt,name=total,proto3" json:"total,omitempty"`
	// Read IO bandwidth capacity in 32k blocksize
	In float64 `protobuf:"fixed64,2,opt,name=in,proto3" json:"in,omitempty"`
	// Write IO bandwidth capacity in 32k blocksize
	Out float64 `protobuf:"fixed64,3,opt,name=out,proto3" json:"out,omitempty"`
	// Pressure indicates how much the resource is in pressure
	Pressure float64 `protobuf:"fixed64,4,opt,name=pressure,proto3" json:"pressure,omitempty"`
	// Default is no entry, for disk IO
	ActualSize string `protobuf:"bytes,5,opt,name=actual_size,json=actualSize,proto3" json:"actual_size,omitempty"`
}

func (x *IOStatus) Reset() {
	*x = IOStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_aggregator_aggregator_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IOStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IOStatus) ProtoMessage() {}

func (x *IOStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_aggregator_aggregator_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IOStatus.ProtoReflect.Descriptor instead.
func (*IOStatus) Descriptor() ([]byte, []int) {
	return file_pkg_api_aggregator_aggregator_proto_rawDescGZIP(), []int{4}
}

func (x *IOStatus) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *IOStatus) GetIn() float64 {
	if x != nil {
		return x.In
	}
	return 0
}

func (x *IOStatus) GetOut() float64 {
	if x != nil {
		return x.Out
	}
	return 0
}

func (x *IOStatus) GetPressure() float64 {
	if x != nil {
		return x.Pressure
	}
	return 0
}

func (x *IOStatus) GetActualSize() string {
	if x != nil {
		return x.ActualSize
	}
	return ""
}

type PodList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Generation int64 `protobuf:"varint,1,opt,name=generation,proto3" json:"generation,omitempty"`
	// key -> pod uid
	PodList map[string]*PodRequest `protobuf:"bytes,2,rep,name=pod_list,json=podList,proto3" json:"pod_list,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *PodList) Reset() {
	*x = PodList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_aggregator_aggregator_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PodList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodList) ProtoMessage() {}

func (x *PodList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_aggregator_aggregator_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodList.ProtoReflect.Descriptor instead.
func (*PodList) Descriptor() ([]byte, []int) {
	return file_pkg_api_aggregator_aggregator_proto_rawDescGZIP(), []int{5}
}

func (x *PodList) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *PodList) GetPodList() map[string]*PodRequest {
	if x != nil {
		return x.PodList
	}
	return nil
}

type PodRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// pod name is required by node agent
	PodName      string               `protobuf:"bytes,1,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodNamespace string               `protobuf:"bytes,2,opt,name=pod_namespace,json=podNamespace,proto3" json:"pod_namespace,omitempty"`
	Request      []*IOResourceRequest `protobuf:"bytes,3,rep,name=request,proto3" json:"request,omitempty"`
}

func (x *PodRequest) Reset() {
	*x = PodRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_aggregator_aggregator_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodRequest) ProtoMessage() {}

func (x *PodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_aggregator_aggregator_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodRequest.ProtoReflect.Descriptor instead.
func (*PodRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_aggregator_aggregator_proto_rawDescGZIP(), []int{6}
}

func (x *PodRequest) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *PodRequest) GetPodNamespace() string {
	if x != nil {
		return x.PodNamespace
	}
	return ""
}

func (x *PodRequest) GetRequest() []*IOResourceRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type IOResourceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IoType       IOType             `protobuf:"varint,1,opt,name=io_type,json=ioType,proto3,enum=aggregator.IOType" json:"io_type,omitempty"`
	WorkloadType int32              `protobuf:"varint,2,opt,name=workload_type,json=workloadType,proto3" json:"workload_type,omitempty"`
	DevRequest   *DeviceRequirement `protobuf:"bytes,3,opt,name=dev_request,json=devRequest,proto3" json:"dev_request,omitempty"`
}

func (x *IOResourceRequest) Reset() {
	*x = IOResourceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_aggregator_aggregator_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IOResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IOResourceRequest) ProtoMessage() {}

func (x *IOResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_aggregator_aggregator_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IOResourceRequest.ProtoReflect.Descriptor instead.
func (*IOResourceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_aggregator_aggregator_proto_rawDescGZIP(), []int{7}
}

func (x *IOResourceRequest) GetIoType() IOType {
	if x != nil {
		return x.IoType
	}
	return IOType_All
}

func (x *IOResourceRequest) GetWorkloadType() int32 {
	if x != nil {
		return x.WorkloadType
	}
	return 0
}

func (x *IOResourceRequest) GetDevRequest() *DeviceRequirement {
	if x != nil {
		return x.DevRequest
	}
	return nil
}

type DeviceRequirement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Network/Block device name
	DevName    string    `protobuf:"bytes,1,opt,name=dev_name,json=devName,proto3" json:"dev_name,omitempty"`
	Request    *Quantity `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	Limit      *Quantity `protobuf:"bytes,3,opt,name=limit,proto3" json:"limit,omitempty"`
	RawRequest *Quantity `protobuf:"bytes,4,opt,name=raw_request,json=rawRequest,proto3" json:"raw_request,omitempty"`
	RawLimit   *Quantity `protobuf:"bytes,5,opt,name=raw_limit,json=rawLimit,proto3" json:"raw_limit,omitempty"`
}

func (x *DeviceRequirement) Reset() {
	*x = DeviceRequirement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_aggregator_aggregator_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceRequirement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceRequirement) ProtoMessage() {}

func (x *DeviceRequirement) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_aggregator_aggregator_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceRequirement.ProtoReflect.Descriptor instead.
func (*DeviceRequirement) Descriptor() ([]byte, []int) {
	return file_pkg_api_aggregator_aggregator_proto_rawDescGZIP(), []int{8}
}

func (x *DeviceRequirement) GetDevName() string {
	if x != nil {
		return x.DevName
	}
	return ""
}

func (x *DeviceRequirement) GetRequest() *Quantity {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *DeviceRequirement) GetLimit() *Quantity {
	if x != nil {
		return x.Limit
	}
	return nil
}

func (x *DeviceRequirement) GetRawRequest() *Quantity {
	if x != nil {
		return x.RawRequest
	}
	return nil
}

func (x *DeviceRequirement) GetRawLimit() *Quantity {
	if x != nil {
		return x.RawLimit
	}
	return nil
}

type Quantity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Converted io request read/ingress bandwidth
	Inbps float64 `protobuf:"fixed64,1,opt,name=inbps,proto3" json:"inbps,omitempty"`
	// Converted io request write/egress bandwidth
	Outbps float64 `protobuf:"fixed64,2,opt,name=outbps,proto3" json:"outbps,omitempty"`
	// Converted io request read/ingress iops, only for BlockIO
	Iniops float64 `protobuf:"fixed64,3,opt,name=iniops,proto3" json:"iniops,omitempty"`
	// Converted io request write/egress iops, only for BlockIO
	Outiops float64 `protobuf:"fixed64,4,opt,name=outiops,proto3" json:"outiops,omitempty"`
}

func (x *Quantity) Reset() {
	*x = Quantity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_aggregator_aggregator_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Quantity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quantity) ProtoMessage() {}

func (x *Quantity) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_aggregator_aggregator_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quantity.ProtoReflect.Descriptor instead.
func (*Quantity) Descriptor() ([]byte, []int) {
	return file_pkg_api_aggregator_aggregator_proto_rawDescGZIP(), []int{9}
}

func (x *Quantity) GetInbps() float64 {
	if x != nil {
		return x.Inbps
	}
	return 0
}

func (x *Quantity) GetOutbps() float64 {
	if x != nil {
		return x.Outbps
	}
	return 0
}

func (x *Quantity) GetIniops() float64 {
	if x != nil {
		return x.Iniops
	}
	return 0
}

func (x *Quantity) GetOutiops() float64 {
	if x != nil {
		return x.Outiops
	}
	return 0
}

type GetReservedPodsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeName string `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
}

func (x *GetReservedPodsRequest) Reset() {
	*x = GetReservedPodsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_aggregator_aggregator_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReservedPodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReservedPodsRequest) ProtoMessage() {}

func (x *GetReservedPodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_aggregator_aggregator_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReservedPodsRequest.ProtoReflect.Descriptor instead.
func (*GetReservedPodsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_aggregator_aggregator_proto_rawDescGZIP(), []int{10}
}

func (x *GetReservedPodsRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

type GetReservedPodsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PodList *PodList `protobuf:"bytes,2,opt,name=pod_list,json=podList,proto3" json:"pod_list,omitempty"`
}

func (x *GetReservedPodsResponse) Reset() {
	*x = GetReservedPodsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_aggregator_aggregator_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReservedPodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReservedPodsResponse) ProtoMessage() {}

func (x *GetReservedPodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_aggregator_aggregator_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReservedPodsResponse.ProtoReflect.Descriptor instead.
func (*GetReservedPodsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_aggregator_aggregator_proto_rawDescGZIP(), []int{11}
}

func (x *GetReservedPodsResponse) GetPodList() *PodList {
	if x != nil {
		return x.PodList
	}
	return nil
}

var File_pkg_api_aggregator_aggregator_proto protoreflect.FileDescriptor

var file_pkg_api_aggregator_aggregator_proto_rawDesc = []byte{
	0x0a, 0x23, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67,
	0x61, 0x74, 0x6f, 0x72, 0x2f, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x6f, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x6f,
	0x72, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x97, 0x01, 0x0a, 0x19, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x4f, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x64, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x64,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2f, 0x0a, 0x13, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x64, 0x5f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x12, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x47, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x05, 0x69, 0x6f, 0x5f, 0x62, 0x77, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74,
	0x6f, 0x72, 0x2e, 0x49, 0x4f, 0x42, 0x61, 0x6e, 0x64, 0x77, 0x69, 0x64, 0x74, 0x68, 0x52, 0x04,
	0x69, 0x6f, 0x42, 0x77, 0x22, 0xed, 0x01, 0x0a, 0x0b, 0x49, 0x4f, 0x42, 0x61, 0x6e, 0x64, 0x77,
	0x69, 0x64, 0x74, 0x68, 0x12, 0x2b, 0x0a, 0x07, 0x69, 0x6f, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74,
	0x6f, 0x72, 0x2e, 0x49, 0x4f, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x69, 0x6f, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x4f, 0x0a, 0x0e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x62, 0x77, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x61, 0x67, 0x67, 0x72,
	0x65, 0x67, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x49, 0x4f, 0x42, 0x61, 0x6e, 0x64, 0x77, 0x69, 0x64,
	0x74, 0x68, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x42, 0x77, 0x49, 0x6e, 0x66, 0x6f, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x0c, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x42, 0x77, 0x49, 0x6e,
	0x66, 0x6f, 0x1a, 0x60, 0x0a, 0x11, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x42, 0x77, 0x49, 0x6e,
	0x66, 0x6f, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x35, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x61, 0x67, 0x67, 0x72, 0x65,
	0x67, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x42, 0x61, 0x6e, 0x64,
	0x77, 0x69, 0x64, 0x74, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0xbf, 0x01, 0x0a, 0x13, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x42,
	0x61, 0x6e, 0x64, 0x77, 0x69, 0x64, 0x74, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x43, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x2b, 0x2e, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x42, 0x61, 0x6e, 0x64, 0x77, 0x69, 0x64, 0x74, 0x68, 0x49, 0x6e, 0x66,
	0x6f, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x1a, 0x4f, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2a, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74,
	0x6f, 0x72, 0x2e, 0x49, 0x4f, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x7f, 0x0a, 0x08, 0x49, 0x4f, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x02, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x75, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6f, 0x75, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72,
	0x65, 0x73, 0x73, 0x75, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x70, 0x72,
	0x65, 0x73, 0x73, 0x75, 0x72, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x63, 0x74, 0x75, 0x61, 0x6c,
	0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x63, 0x74,
	0x75, 0x61, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x22, 0xba, 0x01, 0x0a, 0x07, 0x50, 0x6f, 0x64, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x3b, 0x0a, 0x08, 0x70, 0x6f, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74,
	0x6f, 0x72, 0x2e, 0x50, 0x6f, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x2e, 0x50, 0x6f, 0x64, 0x4c, 0x69,
	0x73, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x70, 0x6f, 0x64, 0x4c, 0x69, 0x73, 0x74,
	0x1a, 0x52, 0x0a, 0x0c, 0x50, 0x6f, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x2c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x50,
	0x6f, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0x85, 0x01, 0x0a, 0x0a, 0x50, 0x6f, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x6f, 0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x6f, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x23,
	0x0a, 0x0d, 0x70, 0x6f, 0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x6f, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x12, 0x37, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x6f,
	0x72, 0x2e, 0x49, 0x4f, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xa5, 0x01, 0x0a,
	0x11, 0x49, 0x4f, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x2b, 0x0a, 0x07, 0x69, 0x6f, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x6f, 0x72,
	0x2e, 0x49, 0x4f, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x69, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x23, 0x0a, 0x0d, 0x77, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x77, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x3e, 0x0a, 0x0b, 0x64, 0x65, 0x76, 0x5f, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x61, 0x67, 0x67, 0x72,
	0x65, 0x67, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x69, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0a, 0x64, 0x65, 0x76, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0xf4, 0x01, 0x0a, 0x11, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x65,
	0x76, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65,
	0x76, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61,
	0x74, 0x6f, 0x72, 0x2e, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x07, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x6f,
	0x72, 0x2e, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x12, 0x35, 0x0a, 0x0b, 0x72, 0x61, 0x77, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61,
	0x74, 0x6f, 0x72, 0x2e, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x0a, 0x72, 0x61,
	0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x09, 0x72, 0x61, 0x77, 0x5f,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x67,
	0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x52, 0x08, 0x72, 0x61, 0x77, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x6a, 0x0a, 0x08, 0x51,
	0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x62, 0x70, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x69, 0x6e, 0x62, 0x70, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x6f, 0x75, 0x74, 0x62, 0x70, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x6f,
	0x75, 0x74, 0x62, 0x70, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x6e, 0x69, 0x6f, 0x70, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x69, 0x6e, 0x69, 0x6f, 0x70, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x6f, 0x75, 0x74, 0x69, 0x6f, 0x70, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07,
	0x6f, 0x75, 0x74, 0x69, 0x6f, 0x70, 0x73, 0x22, 0x35, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x50, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x49,
	0x0a, 0x17, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x50, 0x6f, 0x64,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x70, 0x6f, 0x64,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x61, 0x67,
	0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x50, 0x6f, 0x64, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x07, 0x70, 0x6f, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x2a, 0x46, 0x0a, 0x06, 0x49, 0x4f, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x6c, 0x6c, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x44, 0x69, 0x73, 0x6b, 0x49, 0x4f, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x49, 0x4f, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x52, 0x44, 0x54, 0x10, 0x03,
	0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x44, 0x54, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x10,
	0x04, 0x32, 0xc0, 0x01, 0x0a, 0x12, 0x49, 0x4f, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74,
	0x6f, 0x72, 0x34, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x4e, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x4f, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x25,
	0x2e, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x4f, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74,
	0x6f, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x5a, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x50, 0x6f, 0x64, 0x73, 0x12, 0x22, 0x2e, 0x61, 0x67,
	0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x64, 0x50, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x23, 0x2e, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x50, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x37, 0x5a, 0x35, 0x73, 0x69, 0x67, 0x73, 0x2e, 0x6b, 0x38, 0x73,
	0x2e, 0x69, 0x6f, 0x2f, 0x49, 0x4f, 0x49, 0x73, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74,
	0x6f, 0x72, 0x3b, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x6f, 0x72, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_api_aggregator_aggregator_proto_rawDescOnce sync.Once
	file_pkg_api_aggregator_aggregator_proto_rawDescData = file_pkg_api_aggregator_aggregator_proto_rawDesc
)

func file_pkg_api_aggregator_aggregator_proto_rawDescGZIP() []byte {
	file_pkg_api_aggregator_aggregator_proto_rawDescOnce.Do(func() {
		file_pkg_api_aggregator_aggregator_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_api_aggregator_aggregator_proto_rawDescData)
	})
	return file_pkg_api_aggregator_aggregator_proto_rawDescData
}

var file_pkg_api_aggregator_aggregator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_api_aggregator_aggregator_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_pkg_api_aggregator_aggregator_proto_goTypes = []interface{}{
	(IOType)(0),                       // 0: aggregator.IOType
	(*Empty)(nil),                     // 1: aggregator.Empty
	(*UpdateNodeIOStatusRequest)(nil), // 2: aggregator.UpdateNodeIOStatusRequest
	(*IOBandwidth)(nil),               // 3: aggregator.IOBandwidth
	(*DeviceBandwidthInfo)(nil),       // 4: aggregator.DeviceBandwidthInfo
	(*IOStatus)(nil),                  // 5: aggregator.IOStatus
	(*PodList)(nil),                   // 6: aggregator.PodList
	(*PodRequest)(nil),                // 7: aggregator.PodRequest
	(*IOResourceRequest)(nil),         // 8: aggregator.IOResourceRequest
	(*DeviceRequirement)(nil),         // 9: aggregator.DeviceRequirement
	(*Quantity)(nil),                  // 10: aggregator.Quantity
	(*GetReservedPodsRequest)(nil),    // 11: aggregator.GetReservedPodsRequest
	(*GetReservedPodsResponse)(nil),   // 12: aggregator.GetReservedPodsResponse
	nil,                               // 13: aggregator.IOBandwidth.DeviceBwInfoEntry
	nil,                               // 14: aggregator.DeviceBandwidthInfo.StatusEntry
	nil,                               // 15: aggregator.PodList.PodListEntry
}
var file_pkg_api_aggregator_aggregator_proto_depIdxs = []int32{
	3,  // 0: aggregator.UpdateNodeIOStatusRequest.io_bw:type_name -> aggregator.IOBandwidth
	0,  // 1: aggregator.IOBandwidth.io_type:type_name -> aggregator.IOType
	13, // 2: aggregator.IOBandwidth.device_bw_info:type_name -> aggregator.IOBandwidth.DeviceBwInfoEntry
	14, // 3: aggregator.DeviceBandwidthInfo.status:type_name -> aggregator.DeviceBandwidthInfo.StatusEntry
	15, // 4: aggregator.PodList.pod_list:type_name -> aggregator.PodList.PodListEntry
	8,  // 5: aggregator.PodRequest.request:type_name -> aggregator.IOResourceRequest
	0,  // 6: aggregator.IOResourceRequest.io_type:type_name -> aggregator.IOType
	9,  // 7: aggregator.IOResourceRequest.dev_request:type_name -> aggregator.DeviceRequirement
	10, // 8: aggregator.DeviceRequirement.request:type_name -> aggregator.Quantity
	10, // 9: aggregator.DeviceRequirement.limit:type_name -> aggregator.Quantity
	10, // 10: aggregator.DeviceRequirement.raw_request:type_name -> aggregator.Quantity
	10, // 11: aggregator.DeviceRequirement.raw_limit:type_name -> aggregator.Quantity
	6,  // 12: aggregator.GetReservedPodsResponse.pod_list:type_name -> aggregator.PodList
	4,  // 13: aggregator.IOBandwidth.DeviceBwInfoEntry.value:type_name -> aggregator.DeviceBandwidthInfo
	5,  // 14: aggregator.DeviceBandwidthInfo.StatusEntry.value:type_name -> aggregator.IOStatus
	7,  // 15: aggregator.PodList.PodListEntry.value:type_name -> aggregator.PodRequest
	2,  // 16: aggregator.IOAggregator4Agent.UpdateNodeIOStatus:input_type -> aggregator.UpdateNodeIOStatusRequest
	11, // 17: aggregator.IOAggregator4Agent.GetReservedPods:input_type -> aggregator.GetReservedPodsRequest
	1,  // 18: aggregator.IOAggregator4Agent.UpdateNodeIOStatus:output_type -> aggregator.Empty
	12, // 19: aggregator.IOAggregator4Agent.GetReservedPods:output_type -> aggregator.GetReservedPodsResponse
	18, // [18:20] is the sub-list for method output_type
	16, // [16:18] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_pkg_api_aggregator_aggregator_proto_init() }
func file_pkg_api_aggregator_aggregator_proto_init() {
	if File_pkg_api_aggregator_aggregator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_api_aggregator_aggregator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_aggregator_aggregator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateNodeIOStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_aggregator_aggregator_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IOBandwidth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_aggregator_aggregator_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceBandwidthInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_aggregator_aggregator_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IOStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_aggregator_aggregator_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PodList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_aggregator_aggregator_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PodRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_aggregator_aggregator_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IOResourceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_aggregator_aggregator_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceRequirement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_aggregator_aggregator_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Quantity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_aggregator_aggregator_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReservedPodsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_aggregator_aggregator_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReservedPodsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_api_aggregator_aggregator_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_aggregator_aggregator_proto_goTypes,
		DependencyIndexes: file_pkg_api_aggregator_aggregator_proto_depIdxs,
		EnumInfos:         file_pkg_api_aggregator_aggregator_proto_enumTypes,
		MessageInfos:      file_pkg_api_aggregator_aggregator_proto_msgTypes,
	}.Build()
	File_pkg_api_aggregator_aggregator_proto = out.File
	file_pkg_api_aggregator_aggregator_proto_rawDesc = nil
	file_pkg_api_aggregator_aggregator_proto_goTypes = nil
	file_pkg_api_aggregator_aggregator_proto_depIdxs = nil
}
