apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: /var/run/kubernetes/scheduler.kubeconfig
leaderElection:
  leaderElect: false
profiles:
- schedulerName: default-scheduler
  plugins:
    multiPoint:
      enabled:
      - name: ResourceIO
  pluginConfig:
    - name: ResourceIO
      args:
        scoreStrategy: LeastAllocated
        resourceType: BlockIO
          