//go:build !ignore_autogenerated

/*
Copyright (C) 2025 Intel Corporation
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Device) DeepCopyInto(out *Device) {
	*out = *in
	if in.ReadRatio != nil {
		in, out := &in.ReadRatio, &out.ReadRatio
		*out = make(map[string]float64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.WriteRatio != nil {
		in, out := &in.WriteRatio, &out.WriteRatio
		*out = make(map[string]float64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Device.
func (in *Device) DeepCopy() *Device {
	if in == nil {
		return nil
	}
	out := new(Device)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceAllocatableBandwidth) DeepCopyInto(out *DeviceAllocatableBandwidth) {
	*out = *in
	if in.DeviceIOStatus != nil {
		in, out := &in.DeviceIOStatus, &out.DeviceIOStatus
		*out = make(map[string]IOAllocatableBandwidth, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceAllocatableBandwidth.
func (in *DeviceAllocatableBandwidth) DeepCopy() *DeviceAllocatableBandwidth {
	if in == nil {
		return nil
	}
	out := new(DeviceAllocatableBandwidth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceState) DeepCopyInto(out *DeviceState) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceState.
func (in *DeviceState) DeepCopy() *DeviceState {
	if in == nil {
		return nil
	}
	out := new(DeviceState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOAllocatableBandwidth) DeepCopyInto(out *IOAllocatableBandwidth) {
	*out = *in
	if in.IOPoolStatus != nil {
		in, out := &in.IOPoolStatus, &out.IOPoolStatus
		*out = make(map[WorkloadQoSType]IOStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOAllocatableBandwidth.
func (in *IOAllocatableBandwidth) DeepCopy() *IOAllocatableBandwidth {
	if in == nil {
		return nil
	}
	out := new(IOAllocatableBandwidth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOStatus) DeepCopyInto(out *IOStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOStatus.
func (in *IOStatus) DeepCopy() *IOStatus {
	if in == nil {
		return nil
	}
	out := new(IOStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeIOStatus) DeepCopyInto(out *NodeIOStatus) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeIOStatus.
func (in *NodeIOStatus) DeepCopy() *NodeIOStatus {
	if in == nil {
		return nil
	}
	out := new(NodeIOStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeIOStatus) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeIOStatusList) DeepCopyInto(out *NodeIOStatusList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeIOStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeIOStatusList.
func (in *NodeIOStatusList) DeepCopy() *NodeIOStatusList {
	if in == nil {
		return nil
	}
	out := new(NodeIOStatusList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeIOStatusList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeIOStatusSpec) DeepCopyInto(out *NodeIOStatusSpec) {
	*out = *in
	if in.ReservedPods != nil {
		in, out := &in.ReservedPods, &out.ReservedPods
		*out = make(map[string]PodRequest, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeIOStatusSpec.
func (in *NodeIOStatusSpec) DeepCopy() *NodeIOStatusSpec {
	if in == nil {
		return nil
	}
	out := new(NodeIOStatusSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeIOStatusStatus) DeepCopyInto(out *NodeIOStatusStatus) {
	*out = *in
	if in.AllocatableBandwidth != nil {
		in, out := &in.AllocatableBandwidth, &out.AllocatableBandwidth
		*out = make(map[WorkloadIOType]DeviceAllocatableBandwidth, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeIOStatusStatus.
func (in *NodeIOStatusStatus) DeepCopy() *NodeIOStatusStatus {
	if in == nil {
		return nil
	}
	out := new(NodeIOStatusStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeStaticIOInfo) DeepCopyInto(out *NodeStaticIOInfo) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeStaticIOInfo.
func (in *NodeStaticIOInfo) DeepCopy() *NodeStaticIOInfo {
	if in == nil {
		return nil
	}
	out := new(NodeStaticIOInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeStaticIOInfo) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeStaticIOInfoList) DeepCopyInto(out *NodeStaticIOInfoList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeStaticIOInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeStaticIOInfoList.
func (in *NodeStaticIOInfoList) DeepCopy() *NodeStaticIOInfoList {
	if in == nil {
		return nil
	}
	out := new(NodeStaticIOInfoList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeStaticIOInfoList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeStaticIOInfoSpec) DeepCopyInto(out *NodeStaticIOInfoSpec) {
	*out = *in
	if in.ResourceConfig != nil {
		in, out := &in.ResourceConfig, &out.ResourceConfig
		*out = make(map[string]ResourceConfigSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeStaticIOInfoSpec.
func (in *NodeStaticIOInfoSpec) DeepCopy() *NodeStaticIOInfoSpec {
	if in == nil {
		return nil
	}
	out := new(NodeStaticIOInfoSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeStaticIOInfoStatus) DeepCopyInto(out *NodeStaticIOInfoStatus) {
	*out = *in
	if in.DeviceStates != nil {
		in, out := &in.DeviceStates, &out.DeviceStates
		*out = make(map[string]DeviceState, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeStaticIOInfoStatus.
func (in *NodeStaticIOInfoStatus) DeepCopy() *NodeStaticIOInfoStatus {
	if in == nil {
		return nil
	}
	out := new(NodeStaticIOInfoStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodRequest) DeepCopyInto(out *PodRequest) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodRequest.
func (in *PodRequest) DeepCopy() *PodRequest {
	if in == nil {
		return nil
	}
	out := new(PodRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceConfigSpec) DeepCopyInto(out *ResourceConfigSpec) {
	*out = *in
	if in.Devices != nil {
		in, out := &in.Devices, &out.Devices
		*out = make(map[string]Device, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Classes != nil {
		in, out := &in.Classes, &out.Classes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceConfigSpec.
func (in *ResourceConfigSpec) DeepCopy() *ResourceConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ResourceConfigSpec)
	in.DeepCopyInto(out)
	return out
}
