/*
Copyright (C) 2025 Intel Corporation
SPDX-License-Identifier: Apache-2.0
*/

//
// ioisolation.proto
//
// communicate with node agent
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.15.8
// source: pkg/api/ioiservice/ioisolation.proto

package ioiservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseState int32

const (
	ResponseState_OK   ResponseState = 0
	ResponseState_FAIL ResponseState = 1
)

// Enum value maps for ResponseState.
var (
	ResponseState_name = map[int32]string{
		0: "OK",
		1: "FAIL",
	}
	ResponseState_value = map[string]int32{
		"OK":   0,
		"FAIL": 1,
	}
)

func (x ResponseState) Enum() *ResponseState {
	p := new(ResponseState)
	*p = x
	return p
}

func (x ResponseState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseState) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_ioiservice_ioisolation_proto_enumTypes[0].Descriptor()
}

func (ResponseState) Type() protoreflect.EnumType {
	return &file_pkg_api_ioiservice_ioisolation_proto_enumTypes[0]
}

func (x ResponseState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseState.Descriptor instead.
func (ResponseState) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_ioiservice_ioisolation_proto_rawDescGZIP(), []int{0}
}

type ConfigureRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Configure string `protobuf:"bytes,2,opt,name=configure,proto3" json:"configure,omitempty"`
	IoiType   int32  `protobuf:"varint,3,opt,name=ioi_type,json=ioiType,proto3" json:"ioi_type,omitempty"`
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_ioiservice_ioisolation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_ioiservice_ioisolation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_ioiservice_ioisolation_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigureRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ConfigureRequest) GetConfigure() string {
	if x != nil {
		return x.Configure
	}
	return ""
}

func (x *ConfigureRequest) GetIoiType() int32 {
	if x != nil {
		return x.IoiType
	}
	return 0
}

type ConfigureResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status       ResponseState `protobuf:"varint,1,opt,name=status,proto3,enum=ResponseState" json:"status,omitempty"`
	ResponseInfo string        `protobuf:"bytes,2,opt,name=responseInfo,proto3" json:"responseInfo,omitempty"`
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_ioiservice_ioisolation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_ioiservice_ioisolation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureResponse.ProtoReflect.Descriptor instead.
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_ioiservice_ioisolation_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigureResponse) GetStatus() ResponseState {
	if x != nil {
		return x.Status
	}
	return ResponseState_OK
}

func (x *ConfigureResponse) GetResponseInfo() string {
	if x != nil {
		return x.ResponseInfo
	}
	return ""
}

type ServiceInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IoiType int32  `protobuf:"varint,1,opt,name=ioi_type,json=ioiType,proto3" json:"ioi_type,omitempty"` // 0 for disk, 1 for network
	Req     string `protobuf:"bytes,2,opt,name=req,proto3" json:"req,omitempty"`
}

func (x *ServiceInfoRequest) Reset() {
	*x = ServiceInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_ioiservice_ioisolation_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfoRequest) ProtoMessage() {}

func (x *ServiceInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_ioiservice_ioisolation_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfoRequest.ProtoReflect.Descriptor instead.
func (*ServiceInfoRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_ioiservice_ioisolation_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceInfoRequest) GetIoiType() int32 {
	if x != nil {
		return x.IoiType
	}
	return 0
}

func (x *ServiceInfoRequest) GetReq() string {
	if x != nil {
		return x.Req
	}
	return ""
}

type ServiceInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type          int32  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"` // 0 for disk, 1 for network
	Version       string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Mode          int32  `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`                  // adq or software
	Configuration string `protobuf:"bytes,4,opt,name=configuration,proto3" json:"configuration,omitempty"` // include tc id, name and type
	// for network io:
	// {
	// mac_addr: "d4:5d:df:09:9e:19",
	// interface_name: "eno2",
	// default_speed: 1000,
	// group_settable: true
	// queue_num: 16 // this field is used to calculate queue_num in Configure: queue num of each group = (queue_num - 2)/2  -((queue_num - 2)/2)%2
	// }
	Status ResponseState `protobuf:"varint,5,opt,name=status,proto3,enum=ResponseState" json:"status,omitempty"`
}

func (x *ServiceInfoResponse) Reset() {
	*x = ServiceInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_ioiservice_ioisolation_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfoResponse) ProtoMessage() {}

func (x *ServiceInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_ioiservice_ioisolation_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfoResponse.ProtoReflect.Descriptor instead.
func (*ServiceInfoResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_ioiservice_ioisolation_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceInfoResponse) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ServiceInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServiceInfoResponse) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *ServiceInfoResponse) GetConfiguration() string {
	if x != nil {
		return x.Configuration
	}
	return ""
}

func (x *ServiceInfoResponse) GetStatus() ResponseState {
	if x != nil {
		return x.Status
	}
	return ResponseState_OK
}

type RegisterAppRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppName string `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	// app_info
	AppInfo string `protobuf:"bytes,2,opt,name=app_info,json=appInfo,proto3" json:"app_info,omitempty"`
	IoiType int32  `protobuf:"varint,3,opt,name=ioi_type,json=ioiType,proto3" json:"ioi_type,omitempty"`
}

func (x *RegisterAppRequest) Reset() {
	*x = RegisterAppRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_ioiservice_ioisolation_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAppRequest) ProtoMessage() {}

func (x *RegisterAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_ioiservice_ioisolation_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAppRequest.ProtoReflect.Descriptor instead.
func (*RegisterAppRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_ioiservice_ioisolation_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterAppRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *RegisterAppRequest) GetAppInfo() string {
	if x != nil {
		return x.AppInfo
	}
	return ""
}

func (x *RegisterAppRequest) GetIoiType() int32 {
	if x != nil {
		return x.IoiType
	}
	return 0
}

type RegisterAppResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status ResponseState `protobuf:"varint,1,opt,name=status,proto3,enum=ResponseState" json:"status,omitempty"`
	AppId  string        `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
}

func (x *RegisterAppResponse) Reset() {
	*x = RegisterAppResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_ioiservice_ioisolation_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAppResponse) ProtoMessage() {}

func (x *RegisterAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_ioiservice_ioisolation_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAppResponse.ProtoReflect.Descriptor instead.
func (*RegisterAppResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_ioiservice_ioisolation_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterAppResponse) GetStatus() ResponseState {
	if x != nil {
		return x.Status
	}
	return ResponseState_OK
}

func (x *RegisterAppResponse) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type UnRegisterAppRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IoiType int32  `protobuf:"varint,3,opt,name=ioi_type,json=ioiType,proto3" json:"ioi_type,omitempty"`
	AppId   string `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
}

func (x *UnRegisterAppRequest) Reset() {
	*x = UnRegisterAppRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_ioiservice_ioisolation_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnRegisterAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnRegisterAppRequest) ProtoMessage() {}

func (x *UnRegisterAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_ioiservice_ioisolation_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnRegisterAppRequest.ProtoReflect.Descriptor instead.
func (*UnRegisterAppRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_ioiservice_ioisolation_proto_rawDescGZIP(), []int{6}
}

func (x *UnRegisterAppRequest) GetIoiType() int32 {
	if x != nil {
		return x.IoiType
	}
	return 0
}

func (x *UnRegisterAppRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type UnRegisterAppResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status ResponseState `protobuf:"varint,1,opt,name=status,proto3,enum=ResponseState" json:"status,omitempty"`
}

func (x *UnRegisterAppResponse) Reset() {
	*x = UnRegisterAppResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_ioiservice_ioisolation_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnRegisterAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnRegisterAppResponse) ProtoMessage() {}

func (x *UnRegisterAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_ioiservice_ioisolation_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnRegisterAppResponse.ProtoReflect.Descriptor instead.
func (*UnRegisterAppResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_ioiservice_ioisolation_proto_rawDescGZIP(), []int{7}
}

func (x *UnRegisterAppResponse) GetStatus() ResponseState {
	if x != nil {
		return x.Status
	}
	return ResponseState_OK
}

type SetAppLimitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// "group_id.appid"
	// if appid is empty, will only set limit for this group
	// else will set limit for this app
	IoiType int32      `protobuf:"varint,3,opt,name=ioi_type,json=ioiType,proto3" json:"ioi_type,omitempty"`
	AppId   string     `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Limit   []*BWLimit `protobuf:"bytes,2,rep,name=limit,proto3" json:"limit,omitempty"`
}

func (x *SetAppLimitRequest) Reset() {
	*x = SetAppLimitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_ioiservice_ioisolation_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetAppLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAppLimitRequest) ProtoMessage() {}

func (x *SetAppLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_ioiservice_ioisolation_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAppLimitRequest.ProtoReflect.Descriptor instead.
func (*SetAppLimitRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_ioiservice_ioisolation_proto_rawDescGZIP(), []int{8}
}

func (x *SetAppLimitRequest) GetIoiType() int32 {
	if x != nil {
		return x.IoiType
	}
	return 0
}

func (x *SetAppLimitRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *SetAppLimitRequest) GetLimit() []*BWLimit {
	if x != nil {
		return x.Limit
	}
	return nil
}

type SetAppLimitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status ResponseState `protobuf:"varint,1,opt,name=status,proto3,enum=ResponseState" json:"status,omitempty"`
}

func (x *SetAppLimitResponse) Reset() {
	*x = SetAppLimitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_ioiservice_ioisolation_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetAppLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAppLimitResponse) ProtoMessage() {}

func (x *SetAppLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_ioiservice_ioisolation_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAppLimitResponse.ProtoReflect.Descriptor instead.
func (*SetAppLimitResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_ioiservice_ioisolation_proto_rawDescGZIP(), []int{9}
}

func (x *SetAppLimitResponse) GetStatus() ResponseState {
	if x != nil {
		return x.Status
	}
	return ResponseState_OK
}

type GetAppLimitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId string `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
}

func (x *GetAppLimitRequest) Reset() {
	*x = GetAppLimitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_ioiservice_ioisolation_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAppLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppLimitRequest) ProtoMessage() {}

func (x *GetAppLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_ioiservice_ioisolation_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppLimitRequest.ProtoReflect.Descriptor instead.
func (*GetAppLimitRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_ioiservice_ioisolation_proto_rawDescGZIP(), []int{10}
}

func (x *GetAppLimitRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type GetAppLimitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  ResponseState `protobuf:"varint,1,opt,name=status,proto3,enum=ResponseState" json:"status,omitempty"`
	BwLimit []*BWLimit    `protobuf:"bytes,2,rep,name=bw_limit,json=bwLimit,proto3" json:"bw_limit,omitempty"`
}

func (x *GetAppLimitResponse) Reset() {
	*x = GetAppLimitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_ioiservice_ioisolation_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAppLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppLimitResponse) ProtoMessage() {}

func (x *GetAppLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_ioiservice_ioisolation_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppLimitResponse.ProtoReflect.Descriptor instead.
func (*GetAppLimitResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_ioiservice_ioisolation_proto_rawDescGZIP(), []int{11}
}

func (x *GetAppLimitResponse) GetStatus() ResponseState {
	if x != nil {
		return x.Status
	}
	return ResponseState_OK
}

func (x *GetAppLimitResponse) GetBwLimit() []*BWLimit {
	if x != nil {
		return x.BwLimit
	}
	return nil
}

type BWLimit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                           // device key
	In      string `protobuf:"bytes,2,opt,name=in,proto3" json:"in,omitempty"`                           // ingress or rbps
	Out     string `protobuf:"bytes,3,opt,name=out,proto3" json:"out,omitempty"`                         // egress or wbps
	InIops  int64  `protobuf:"varint,4,opt,name=in_iops,json=inIops,proto3" json:"in_iops,omitempty"`    // ingress in iops
	OutIops int64  `protobuf:"varint,5,opt,name=out_iops,json=outIops,proto3" json:"out_iops,omitempty"` // egress out iops
}

func (x *BWLimit) Reset() {
	*x = BWLimit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_ioiservice_ioisolation_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BWLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BWLimit) ProtoMessage() {}

func (x *BWLimit) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_ioiservice_ioisolation_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BWLimit.ProtoReflect.Descriptor instead.
func (*BWLimit) Descriptor() ([]byte, []int) {
	return file_pkg_api_ioiservice_ioisolation_proto_rawDescGZIP(), []int{12}
}

func (x *BWLimit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BWLimit) GetIn() string {
	if x != nil {
		return x.In
	}
	return ""
}

func (x *BWLimit) GetOut() string {
	if x != nil {
		return x.Out
	}
	return ""
}

func (x *BWLimit) GetInIops() int64 {
	if x != nil {
		return x.InIops
	}
	return 0
}

func (x *BWLimit) GetOutIops() int64 {
	if x != nil {
		return x.OutIops
	}
	return 0
}

type SubscribeContext struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ioi_type = 0 => subscribe all payloads
	// ioi_type = 1 => subscribe disk io bw payload
	// ioi_type = 2 => subscribe network io bw payload
	// ioi_type = 3 => subscribe rdt info payload
	// ioi_type = 4 => subscribe rdt quantity info payload
	IoiType int32 `protobuf:"varint,1,opt,name=ioi_type,json=ioiType,proto3" json:"ioi_type,omitempty"`
}

func (x *SubscribeContext) Reset() {
	*x = SubscribeContext{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_ioiservice_ioisolation_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeContext) ProtoMessage() {}

func (x *SubscribeContext) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_ioiservice_ioisolation_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeContext.ProtoReflect.Descriptor instead.
func (*SubscribeContext) Descriptor() ([]byte, []int) {
	return file_pkg_api_ioiservice_ioisolation_proto_rawDescGZIP(), []int{13}
}

func (x *SubscribeContext) GetIoiType() int32 {
	if x != nil {
		return x.IoiType
	}
	return 0
}

type AppsBandwidth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IoiType int32 `protobuf:"varint,1,opt,name=ioi_type,json=ioiType,proto3" json:"ioi_type,omitempty"`
	// Types that are assignable to Payload:
	//
	//	*AppsBandwidth_DiskIoBw
	//	*AppsBandwidth_NetworkIoBw
	//	*AppsBandwidth_RdtInfo
	Payload isAppsBandwidth_Payload `protobuf_oneof:"payload"`
}

func (x *AppsBandwidth) Reset() {
	*x = AppsBandwidth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_ioiservice_ioisolation_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppsBandwidth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppsBandwidth) ProtoMessage() {}

func (x *AppsBandwidth) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_ioiservice_ioisolation_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppsBandwidth.ProtoReflect.Descriptor instead.
func (*AppsBandwidth) Descriptor() ([]byte, []int) {
	return file_pkg_api_ioiservice_ioisolation_proto_rawDescGZIP(), []int{14}
}

func (x *AppsBandwidth) GetIoiType() int32 {
	if x != nil {
		return x.IoiType
	}
	return 0
}

func (m *AppsBandwidth) GetPayload() isAppsBandwidth_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *AppsBandwidth) GetDiskIoBw() *AppDiskIOBandwidth {
	if x, ok := x.GetPayload().(*AppsBandwidth_DiskIoBw); ok {
		return x.DiskIoBw
	}
	return nil
}

func (x *AppsBandwidth) GetNetworkIoBw() *AppNetworkIOBandwidth {
	if x, ok := x.GetPayload().(*AppsBandwidth_NetworkIoBw); ok {
		return x.NetworkIoBw
	}
	return nil
}

func (x *AppsBandwidth) GetRdtInfo() *RDTInfo {
	if x, ok := x.GetPayload().(*AppsBandwidth_RdtInfo); ok {
		return x.RdtInfo
	}
	return nil
}

type isAppsBandwidth_Payload interface {
	isAppsBandwidth_Payload()
}

type AppsBandwidth_DiskIoBw struct {
	DiskIoBw *AppDiskIOBandwidth `protobuf:"bytes,2,opt,name=disk_io_bw,json=diskIoBw,proto3,oneof"`
}

type AppsBandwidth_NetworkIoBw struct {
	NetworkIoBw *AppNetworkIOBandwidth `protobuf:"bytes,3,opt,name=network_io_bw,json=networkIoBw,proto3,oneof"`
}

type AppsBandwidth_RdtInfo struct {
	RdtInfo *RDTInfo `protobuf:"bytes,4,opt,name=rdt_info,json=rdtInfo,proto3,oneof"`
}

func (*AppsBandwidth_DiskIoBw) isAppsBandwidth_Payload() {}

func (*AppsBandwidth_NetworkIoBw) isAppsBandwidth_Payload() {}

func (*AppsBandwidth_RdtInfo) isAppsBandwidth_Payload() {}

type RDTInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// key -> class name, value -> info
	ClassInfo map[string]float64 `protobuf:"bytes,1,rep,name=class_info,json=classInfo,proto3" json:"class_info,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
}

func (x *RDTInfo) Reset() {
	*x = RDTInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_ioiservice_ioisolation_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RDTInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RDTInfo) ProtoMessage() {}

func (x *RDTInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_ioiservice_ioisolation_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RDTInfo.ProtoReflect.Descriptor instead.
func (*RDTInfo) Descriptor() ([]byte, []int) {
	return file_pkg_api_ioiservice_ioisolation_proto_rawDescGZIP(), []int{15}
}

func (x *RDTInfo) GetClassInfo() map[string]float64 {
	if x != nil {
		return x.ClassInfo
	}
	return nil
}

type AppDiskIOBandwidth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// key -> app_id, value -> AppBandwidthInfo
	AppBwInfo map[string]*AppBandwidthInfo `protobuf:"bytes,1,rep,name=app_bw_info,json=appBwInfo,proto3" json:"app_bw_info,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *AppDiskIOBandwidth) Reset() {
	*x = AppDiskIOBandwidth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_ioiservice_ioisolation_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppDiskIOBandwidth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppDiskIOBandwidth) ProtoMessage() {}

func (x *AppDiskIOBandwidth) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_ioiservice_ioisolation_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppDiskIOBandwidth.ProtoReflect.Descriptor instead.
func (*AppDiskIOBandwidth) Descriptor() ([]byte, []int) {
	return file_pkg_api_ioiservice_ioisolation_proto_rawDescGZIP(), []int{16}
}

func (x *AppDiskIOBandwidth) GetAppBwInfo() map[string]*AppBandwidthInfo {
	if x != nil {
		return x.AppBwInfo
	}
	return nil
}

type AppBandwidthInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BwInfo []*BandwidthInfo `protobuf:"bytes,2,rep,name=bw_info,json=bwInfo,proto3" json:"bw_info,omitempty"`
}

func (x *AppBandwidthInfo) Reset() {
	*x = AppBandwidthInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_ioiservice_ioisolation_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppBandwidthInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppBandwidthInfo) ProtoMessage() {}

func (x *AppBandwidthInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_ioiservice_ioisolation_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppBandwidthInfo.ProtoReflect.Descriptor instead.
func (*AppBandwidthInfo) Descriptor() ([]byte, []int) {
	return file_pkg_api_ioiservice_ioisolation_proto_rawDescGZIP(), []int{17}
}

func (x *AppBandwidthInfo) GetBwInfo() []*BandwidthInfo {
	if x != nil {
		return x.BwInfo
	}
	return nil
}

type BandwidthInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// different block size => bw
	Id         string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                                         // device id
	IsRead     bool              `protobuf:"varint,2,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"`                                                                                  // read / write
	Bandwidths map[string]string `protobuf:"bytes,3,rep,name=bandwidths,proto3" json:"bandwidths,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // 1k -> 100M, 4k -> 400M
}

func (x *BandwidthInfo) Reset() {
	*x = BandwidthInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_ioiservice_ioisolation_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BandwidthInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BandwidthInfo) ProtoMessage() {}

func (x *BandwidthInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_ioiservice_ioisolation_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BandwidthInfo.ProtoReflect.Descriptor instead.
func (*BandwidthInfo) Descriptor() ([]byte, []int) {
	return file_pkg_api_ioiservice_ioisolation_proto_rawDescGZIP(), []int{18}
}

func (x *BandwidthInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BandwidthInfo) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *BandwidthInfo) GetBandwidths() map[string]string {
	if x != nil {
		return x.Bandwidths
	}
	return nil
}

type AppNetworkIOBandwidth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// key -> app_id, value -> AppBandwidthInfo
	AppBwInfo map[string]*AppNetworkBandwidthInfo `protobuf:"bytes,1,rep,name=app_bw_info,json=appBwInfo,proto3" json:"app_bw_info,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *AppNetworkIOBandwidth) Reset() {
	*x = AppNetworkIOBandwidth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_ioiservice_ioisolation_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppNetworkIOBandwidth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppNetworkIOBandwidth) ProtoMessage() {}

func (x *AppNetworkIOBandwidth) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_ioiservice_ioisolation_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppNetworkIOBandwidth.ProtoReflect.Descriptor instead.
func (*AppNetworkIOBandwidth) Descriptor() ([]byte, []int) {
	return file_pkg_api_ioiservice_ioisolation_proto_rawDescGZIP(), []int{19}
}

func (x *AppNetworkIOBandwidth) GetAppBwInfo() map[string]*AppNetworkBandwidthInfo {
	if x != nil {
		return x.AppBwInfo
	}
	return nil
}

type AppNetworkBandwidthInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BwInfo []*NetworkBandwidthInfo `protobuf:"bytes,2,rep,name=bw_info,json=bwInfo,proto3" json:"bw_info,omitempty"`
}

func (x *AppNetworkBandwidthInfo) Reset() {
	*x = AppNetworkBandwidthInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_ioiservice_ioisolation_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppNetworkBandwidthInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppNetworkBandwidthInfo) ProtoMessage() {}

func (x *AppNetworkBandwidthInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_ioiservice_ioisolation_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppNetworkBandwidthInfo.ProtoReflect.Descriptor instead.
func (*AppNetworkBandwidthInfo) Descriptor() ([]byte, []int) {
	return file_pkg_api_ioiservice_ioisolation_proto_rawDescGZIP(), []int{20}
}

func (x *AppNetworkBandwidthInfo) GetBwInfo() []*NetworkBandwidthInfo {
	if x != nil {
		return x.BwInfo
	}
	return nil
}

type NetworkBandwidthInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                 // device id
	IsIngress bool   `protobuf:"varint,2,opt,name=is_ingress,json=isIngress,proto3" json:"is_ingress,omitempty"` // ingress=0 / egress=1
	Value     string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`                           // 100Mbps
}

func (x *NetworkBandwidthInfo) Reset() {
	*x = NetworkBandwidthInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_ioiservice_ioisolation_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkBandwidthInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkBandwidthInfo) ProtoMessage() {}

func (x *NetworkBandwidthInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_ioiservice_ioisolation_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkBandwidthInfo.ProtoReflect.Descriptor instead.
func (*NetworkBandwidthInfo) Descriptor() ([]byte, []int) {
	return file_pkg_api_ioiservice_ioisolation_proto_rawDescGZIP(), []int{21}
}

func (x *NetworkBandwidthInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NetworkBandwidthInfo) GetIsIngress() bool {
	if x != nil {
		return x.IsIngress
	}
	return false
}

func (x *NetworkBandwidthInfo) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_pkg_api_ioiservice_ioisolation_proto protoreflect.FileDescriptor

var file_pkg_api_ioiservice_ioisolation_proto_rawDesc = []byte{
	0x0a, 0x24, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x69, 0x6f, 0x69, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2f, 0x69, 0x6f, 0x69, 0x73, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5f, 0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x75, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x69, 0x6f, 0x69, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x69, 0x6f, 0x69, 0x54, 0x79, 0x70, 0x65, 0x22, 0x5f, 0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x75, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x41, 0x0a, 0x12, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19,
	0x0a, 0x08, 0x69, 0x6f, 0x69, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x69, 0x6f, 0x69, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x71,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x65, 0x71, 0x22, 0xa5, 0x01, 0x0a, 0x13,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0x65, 0x0a, 0x12, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x41,
	0x70, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x70, 0x70,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x70, 0x70,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x70, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x19, 0x0a, 0x08, 0x69, 0x6f, 0x69, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x69, 0x6f, 0x69, 0x54, 0x79, 0x70, 0x65, 0x22, 0x54, 0x0a, 0x13, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x41, 0x70, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x26, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64,
	0x22, 0x48, 0x0a, 0x14, 0x55, 0x6e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x41, 0x70,
	0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x6f, 0x69, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x69, 0x6f, 0x69, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x22, 0x3f, 0x0a, 0x15, 0x55, 0x6e,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x41, 0x70, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x66, 0x0a, 0x12, 0x53,
	0x65, 0x74, 0x41, 0x70, 0x70, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x6f, 0x69, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x69, 0x6f, 0x69, 0x54, 0x79, 0x70, 0x65, 0x12, 0x15, 0x0a, 0x06,
	0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70,
	0x70, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x08, 0x2e, 0x42, 0x57, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x22, 0x3d, 0x0a, 0x13, 0x53, 0x65, 0x74, 0x41, 0x70, 0x70, 0x4c, 0x69, 0x6d,
	0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0x2b, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x4c, 0x69, 0x6d, 0x69,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x22,
	0x62, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x23,
	0x0a, 0x08, 0x62, 0x77, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x08, 0x2e, 0x42, 0x57, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x07, 0x62, 0x77, 0x4c, 0x69,
	0x6d, 0x69, 0x74, 0x22, 0x6f, 0x0a, 0x07, 0x42, 0x57, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x6e, 0x12, 0x10,
	0x0a, 0x03, 0x6f, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6f, 0x75, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x69, 0x6e, 0x5f, 0x69, 0x6f, 0x70, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x69, 0x6e, 0x49, 0x6f, 0x70, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x75, 0x74,
	0x5f, 0x69, 0x6f, 0x70, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6f, 0x75, 0x74,
	0x49, 0x6f, 0x70, 0x73, 0x22, 0x2d, 0x0a, 0x10, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x6f, 0x69, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x69, 0x6f, 0x69, 0x54,
	0x79, 0x70, 0x65, 0x22, 0xcf, 0x01, 0x0a, 0x0d, 0x41, 0x70, 0x70, 0x73, 0x42, 0x61, 0x6e, 0x64,
	0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x6f, 0x69, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x69, 0x6f, 0x69, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x33, 0x0a, 0x0a, 0x64, 0x69, 0x73, 0x6b, 0x5f, 0x69, 0x6f, 0x5f, 0x62, 0x77, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x41, 0x70, 0x70, 0x44, 0x69, 0x73, 0x6b, 0x49, 0x4f,
	0x42, 0x61, 0x6e, 0x64, 0x77, 0x69, 0x64, 0x74, 0x68, 0x48, 0x00, 0x52, 0x08, 0x64, 0x69, 0x73,
	0x6b, 0x49, 0x6f, 0x42, 0x77, 0x12, 0x3c, 0x0a, 0x0d, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x5f, 0x69, 0x6f, 0x5f, 0x62, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x41,
	0x70, 0x70, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x4f, 0x42, 0x61, 0x6e, 0x64, 0x77,
	0x69, 0x64, 0x74, 0x68, 0x48, 0x00, 0x52, 0x0b, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49,
	0x6f, 0x42, 0x77, 0x12, 0x25, 0x0a, 0x08, 0x72, 0x64, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x52, 0x44, 0x54, 0x49, 0x6e, 0x66, 0x6f, 0x48,
	0x00, 0x52, 0x07, 0x72, 0x64, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x7f, 0x0a, 0x07, 0x52, 0x44, 0x54, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x36, 0x0a, 0x0a, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x52, 0x44, 0x54, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x43,
	0x6c, 0x61, 0x73, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x09, 0x63,
	0x6c, 0x61, 0x73, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x3c, 0x0a, 0x0e, 0x43, 0x6c, 0x61, 0x73,
	0x73, 0x49, 0x6e, 0x66, 0x6f, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xa9, 0x01, 0x0a, 0x12, 0x41, 0x70, 0x70, 0x44, 0x69,
	0x73, 0x6b, 0x49, 0x4f, 0x42, 0x61, 0x6e, 0x64, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x42, 0x0a,
	0x0b, 0x61, 0x70, 0x70, 0x5f, 0x62, 0x77, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x22, 0x2e, 0x41, 0x70, 0x70, 0x44, 0x69, 0x73, 0x6b, 0x49, 0x4f, 0x42, 0x61,
	0x6e, 0x64, 0x77, 0x69, 0x64, 0x74, 0x68, 0x2e, 0x41, 0x70, 0x70, 0x42, 0x77, 0x49, 0x6e, 0x66,
	0x6f, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x09, 0x61, 0x70, 0x70, 0x42, 0x77, 0x49, 0x6e, 0x66,
	0x6f, 0x1a, 0x4f, 0x0a, 0x0e, 0x41, 0x70, 0x70, 0x42, 0x77, 0x49, 0x6e, 0x66, 0x6f, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x27, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x41, 0x70, 0x70, 0x42, 0x61, 0x6e, 0x64, 0x77, 0x69,
	0x64, 0x74, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x22, 0x3b, 0x0a, 0x10, 0x41, 0x70, 0x70, 0x42, 0x61, 0x6e, 0x64, 0x77, 0x69, 0x64,
	0x74, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x27, 0x0a, 0x07, 0x62, 0x77, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x42, 0x61, 0x6e, 0x64, 0x77, 0x69,
	0x64, 0x74, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x62, 0x77, 0x49, 0x6e, 0x66, 0x6f, 0x22,
	0xb7, 0x01, 0x0a, 0x0d, 0x42, 0x61, 0x6e, 0x64, 0x77, 0x69, 0x64, 0x74, 0x68, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x72, 0x65, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x52, 0x65, 0x61, 0x64, 0x12, 0x3e, 0x0a, 0x0a, 0x62, 0x61,
	0x6e, 0x64, 0x77, 0x69, 0x64, 0x74, 0x68, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e,
	0x2e, 0x42, 0x61, 0x6e, 0x64, 0x77, 0x69, 0x64, 0x74, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x42,
	0x61, 0x6e, 0x64, 0x77, 0x69, 0x64, 0x74, 0x68, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a,
	0x62, 0x61, 0x6e, 0x64, 0x77, 0x69, 0x64, 0x74, 0x68, 0x73, 0x1a, 0x3d, 0x0a, 0x0f, 0x42, 0x61,
	0x6e, 0x64, 0x77, 0x69, 0x64, 0x74, 0x68, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xb6, 0x01, 0x0a, 0x15, 0x41, 0x70,
	0x70, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x4f, 0x42, 0x61, 0x6e, 0x64, 0x77, 0x69,
	0x64, 0x74, 0x68, 0x12, 0x45, 0x0a, 0x0b, 0x61, 0x70, 0x70, 0x5f, 0x62, 0x77, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x41, 0x70, 0x70, 0x4e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x4f, 0x42, 0x61, 0x6e, 0x64, 0x77, 0x69, 0x64, 0x74, 0x68,
	0x2e, 0x41, 0x70, 0x70, 0x42, 0x77, 0x49, 0x6e, 0x66, 0x6f, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x09, 0x61, 0x70, 0x70, 0x42, 0x77, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x56, 0x0a, 0x0e, 0x41, 0x70,
	0x70, 0x42, 0x77, 0x49, 0x6e, 0x66, 0x6f, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2e,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x41, 0x70, 0x70, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x42, 0x61, 0x6e, 0x64, 0x77, 0x69,
	0x64, 0x74, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x22, 0x49, 0x0a, 0x17, 0x41, 0x70, 0x70, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x42, 0x61, 0x6e, 0x64, 0x77, 0x69, 0x64, 0x74, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2e, 0x0a,
	0x07, 0x62, 0x77, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x42, 0x61, 0x6e, 0x64, 0x77, 0x69, 0x64, 0x74,
	0x68, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x62, 0x77, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x5b, 0x0a,
	0x14, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x42, 0x61, 0x6e, 0x64, 0x77, 0x69, 0x64, 0x74,
	0x68, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x69, 0x6e, 0x67, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x49, 0x6e, 0x67,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2a, 0x21, 0x0a, 0x0d, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x06, 0x0a, 0x02, 0x4f,
	0x4b, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x41, 0x49, 0x4c, 0x10, 0x01, 0x32, 0x9d, 0x03,
	0x0a, 0x0a, 0x69, 0x6f, 0x69, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x32, 0x0a, 0x09,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x12, 0x11, 0x2e, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x75, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3b, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x13, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a,
	0x0b, 0x53, 0x65, 0x74, 0x41, 0x70, 0x70, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x13, 0x2e, 0x53,
	0x65, 0x74, 0x41, 0x70, 0x70, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x14, 0x2e, 0x53, 0x65, 0x74, 0x41, 0x70, 0x70, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x41, 0x70,
	0x70, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x13, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x4c,
	0x69, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x47, 0x65,
	0x74, 0x41, 0x70, 0x70, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x38, 0x0a, 0x0b, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x41, 0x70, 0x70,
	0x12, 0x13, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x41, 0x70, 0x70, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x41, 0x70, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x0d, 0x55,
	0x6e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x41, 0x70, 0x70, 0x12, 0x15, 0x2e, 0x55,
	0x6e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x41, 0x70, 0x70, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x55, 0x6e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x41, 0x70, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x09, 0x53,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x11, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x1a, 0x0e, 0x2e, 0x41, 0x70,
	0x70, 0x73, 0x42, 0x61, 0x6e, 0x64, 0x77, 0x69, 0x64, 0x74, 0x68, 0x30, 0x01, 0x42, 0x37, 0x5a,
	0x35, 0x73, 0x69, 0x67, 0x73, 0x2e, 0x6b, 0x38, 0x73, 0x2e, 0x69, 0x6f, 0x2f, 0x49, 0x4f, 0x49,
	0x73, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x69, 0x6f, 0x69, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x3b, 0x69, 0x6f, 0x69, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_api_ioiservice_ioisolation_proto_rawDescOnce sync.Once
	file_pkg_api_ioiservice_ioisolation_proto_rawDescData = file_pkg_api_ioiservice_ioisolation_proto_rawDesc
)

func file_pkg_api_ioiservice_ioisolation_proto_rawDescGZIP() []byte {
	file_pkg_api_ioiservice_ioisolation_proto_rawDescOnce.Do(func() {
		file_pkg_api_ioiservice_ioisolation_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_api_ioiservice_ioisolation_proto_rawDescData)
	})
	return file_pkg_api_ioiservice_ioisolation_proto_rawDescData
}

var file_pkg_api_ioiservice_ioisolation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_api_ioiservice_ioisolation_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_pkg_api_ioiservice_ioisolation_proto_goTypes = []interface{}{
	(ResponseState)(0),              // 0: ResponseState
	(*ConfigureRequest)(nil),        // 1: ConfigureRequest
	(*ConfigureResponse)(nil),       // 2: ConfigureResponse
	(*ServiceInfoRequest)(nil),      // 3: ServiceInfoRequest
	(*ServiceInfoResponse)(nil),     // 4: ServiceInfoResponse
	(*RegisterAppRequest)(nil),      // 5: RegisterAppRequest
	(*RegisterAppResponse)(nil),     // 6: RegisterAppResponse
	(*UnRegisterAppRequest)(nil),    // 7: UnRegisterAppRequest
	(*UnRegisterAppResponse)(nil),   // 8: UnRegisterAppResponse
	(*SetAppLimitRequest)(nil),      // 9: SetAppLimitRequest
	(*SetAppLimitResponse)(nil),     // 10: SetAppLimitResponse
	(*GetAppLimitRequest)(nil),      // 11: GetAppLimitRequest
	(*GetAppLimitResponse)(nil),     // 12: GetAppLimitResponse
	(*BWLimit)(nil),                 // 13: BWLimit
	(*SubscribeContext)(nil),        // 14: SubscribeContext
	(*AppsBandwidth)(nil),           // 15: AppsBandwidth
	(*RDTInfo)(nil),                 // 16: RDTInfo
	(*AppDiskIOBandwidth)(nil),      // 17: AppDiskIOBandwidth
	(*AppBandwidthInfo)(nil),        // 18: AppBandwidthInfo
	(*BandwidthInfo)(nil),           // 19: BandwidthInfo
	(*AppNetworkIOBandwidth)(nil),   // 20: AppNetworkIOBandwidth
	(*AppNetworkBandwidthInfo)(nil), // 21: AppNetworkBandwidthInfo
	(*NetworkBandwidthInfo)(nil),    // 22: NetworkBandwidthInfo
	nil,                             // 23: RDTInfo.ClassInfoEntry
	nil,                             // 24: AppDiskIOBandwidth.AppBwInfoEntry
	nil,                             // 25: BandwidthInfo.BandwidthsEntry
	nil,                             // 26: AppNetworkIOBandwidth.AppBwInfoEntry
}
var file_pkg_api_ioiservice_ioisolation_proto_depIdxs = []int32{
	0,  // 0: ConfigureResponse.status:type_name -> ResponseState
	0,  // 1: ServiceInfoResponse.status:type_name -> ResponseState
	0,  // 2: RegisterAppResponse.status:type_name -> ResponseState
	0,  // 3: UnRegisterAppResponse.status:type_name -> ResponseState
	13, // 4: SetAppLimitRequest.limit:type_name -> BWLimit
	0,  // 5: SetAppLimitResponse.status:type_name -> ResponseState
	0,  // 6: GetAppLimitResponse.status:type_name -> ResponseState
	13, // 7: GetAppLimitResponse.bw_limit:type_name -> BWLimit
	17, // 8: AppsBandwidth.disk_io_bw:type_name -> AppDiskIOBandwidth
	20, // 9: AppsBandwidth.network_io_bw:type_name -> AppNetworkIOBandwidth
	16, // 10: AppsBandwidth.rdt_info:type_name -> RDTInfo
	23, // 11: RDTInfo.class_info:type_name -> RDTInfo.ClassInfoEntry
	24, // 12: AppDiskIOBandwidth.app_bw_info:type_name -> AppDiskIOBandwidth.AppBwInfoEntry
	19, // 13: AppBandwidthInfo.bw_info:type_name -> BandwidthInfo
	25, // 14: BandwidthInfo.bandwidths:type_name -> BandwidthInfo.BandwidthsEntry
	26, // 15: AppNetworkIOBandwidth.app_bw_info:type_name -> AppNetworkIOBandwidth.AppBwInfoEntry
	22, // 16: AppNetworkBandwidthInfo.bw_info:type_name -> NetworkBandwidthInfo
	18, // 17: AppDiskIOBandwidth.AppBwInfoEntry.value:type_name -> AppBandwidthInfo
	21, // 18: AppNetworkIOBandwidth.AppBwInfoEntry.value:type_name -> AppNetworkBandwidthInfo
	1,  // 19: ioiservice.Configure:input_type -> ConfigureRequest
	3,  // 20: ioiservice.GetServiceInfo:input_type -> ServiceInfoRequest
	9,  // 21: ioiservice.SetAppLimit:input_type -> SetAppLimitRequest
	11, // 22: ioiservice.GetAppLimit:input_type -> GetAppLimitRequest
	5,  // 23: ioiservice.RegisterApp:input_type -> RegisterAppRequest
	7,  // 24: ioiservice.UnRegisterApp:input_type -> UnRegisterAppRequest
	14, // 25: ioiservice.Subscribe:input_type -> SubscribeContext
	2,  // 26: ioiservice.Configure:output_type -> ConfigureResponse
	4,  // 27: ioiservice.GetServiceInfo:output_type -> ServiceInfoResponse
	10, // 28: ioiservice.SetAppLimit:output_type -> SetAppLimitResponse
	12, // 29: ioiservice.GetAppLimit:output_type -> GetAppLimitResponse
	6,  // 30: ioiservice.RegisterApp:output_type -> RegisterAppResponse
	8,  // 31: ioiservice.UnRegisterApp:output_type -> UnRegisterAppResponse
	15, // 32: ioiservice.Subscribe:output_type -> AppsBandwidth
	26, // [26:33] is the sub-list for method output_type
	19, // [19:26] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_pkg_api_ioiservice_ioisolation_proto_init() }
func file_pkg_api_ioiservice_ioisolation_proto_init() {
	if File_pkg_api_ioiservice_ioisolation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_api_ioiservice_ioisolation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigureRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_ioiservice_ioisolation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigureResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_ioiservice_ioisolation_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_ioiservice_ioisolation_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_ioiservice_ioisolation_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterAppRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_ioiservice_ioisolation_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterAppResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_ioiservice_ioisolation_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnRegisterAppRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_ioiservice_ioisolation_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnRegisterAppResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_ioiservice_ioisolation_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetAppLimitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_ioiservice_ioisolation_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetAppLimitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_ioiservice_ioisolation_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAppLimitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_ioiservice_ioisolation_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAppLimitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_ioiservice_ioisolation_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BWLimit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_ioiservice_ioisolation_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeContext); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_ioiservice_ioisolation_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppsBandwidth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_ioiservice_ioisolation_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RDTInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_ioiservice_ioisolation_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppDiskIOBandwidth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_ioiservice_ioisolation_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppBandwidthInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_ioiservice_ioisolation_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BandwidthInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_ioiservice_ioisolation_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppNetworkIOBandwidth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_ioiservice_ioisolation_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppNetworkBandwidthInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_ioiservice_ioisolation_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetworkBandwidthInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pkg_api_ioiservice_ioisolation_proto_msgTypes[14].OneofWrappers = []interface{}{
		(*AppsBandwidth_DiskIoBw)(nil),
		(*AppsBandwidth_NetworkIoBw)(nil),
		(*AppsBandwidth_RdtInfo)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_api_ioiservice_ioisolation_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_ioiservice_ioisolation_proto_goTypes,
		DependencyIndexes: file_pkg_api_ioiservice_ioisolation_proto_depIdxs,
		EnumInfos:         file_pkg_api_ioiservice_ioisolation_proto_enumTypes,
		MessageInfos:      file_pkg_api_ioiservice_ioisolation_proto_msgTypes,
	}.Build()
	File_pkg_api_ioiservice_ioisolation_proto = out.File
	file_pkg_api_ioiservice_ioisolation_proto_rawDesc = nil
	file_pkg_api_ioiservice_ioisolation_proto_goTypes = nil
	file_pkg_api_ioiservice_ioisolation_proto_depIdxs = nil
}
