//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright (C) 2025 Intel Corporation
SPDX-License-Identifier: Apache-2.0
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	config "sigs.k8s.io/IOIsolation/api/config"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ResourceIOArgs)(nil), (*config.ResourceIOArgs)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ResourceIOArgs_To_config_ResourceIOArgs(a.(*ResourceIOArgs), b.(*config.ResourceIOArgs), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ResourceIOArgs)(nil), (*ResourceIOArgs)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ResourceIOArgs_To_v1_ResourceIOArgs(a.(*config.ResourceIOArgs), b.(*ResourceIOArgs), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1_ResourceIOArgs_To_config_ResourceIOArgs(in *ResourceIOArgs, out *config.ResourceIOArgs, s conversion.Scope) error {
	if err := metav1.Convert_Pointer_string_To_string(&in.ScoreStrategy, &out.ScoreStrategy, s); err != nil {
		return err
	}
	if err := metav1.Convert_Pointer_string_To_string(&in.ResourceType, &out.ResourceType, s); err != nil {
		return err
	}
	if err := metav1.Convert_Pointer_string_To_string(&in.BinPackingStrategy, &out.BinPackingStrategy, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_ResourceIOArgs_To_config_ResourceIOArgs is an autogenerated conversion function.
func Convert_v1_ResourceIOArgs_To_config_ResourceIOArgs(in *ResourceIOArgs, out *config.ResourceIOArgs, s conversion.Scope) error {
	return autoConvert_v1_ResourceIOArgs_To_config_ResourceIOArgs(in, out, s)
}

func autoConvert_config_ResourceIOArgs_To_v1_ResourceIOArgs(in *config.ResourceIOArgs, out *ResourceIOArgs, s conversion.Scope) error {
	if err := metav1.Convert_string_To_Pointer_string(&in.ScoreStrategy, &out.ScoreStrategy, s); err != nil {
		return err
	}
	if err := metav1.Convert_string_To_Pointer_string(&in.ResourceType, &out.ResourceType, s); err != nil {
		return err
	}
	if err := metav1.Convert_string_To_Pointer_string(&in.BinPackingStrategy, &out.BinPackingStrategy, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_ResourceIOArgs_To_v1_ResourceIOArgs is an autogenerated conversion function.
func Convert_config_ResourceIOArgs_To_v1_ResourceIOArgs(in *config.ResourceIOArgs, out *ResourceIOArgs, s conversion.Scope) error {
	return autoConvert_config_ResourceIOArgs_To_v1_ResourceIOArgs(in, out, s)
}
