//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright (C) 2025 Intel Corporation
SPDX-License-Identifier: Apache-2.0
*/
// Code generated by defaulter-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&ResourceIOArgs{}, func(obj interface{}) { SetObjectDefaults_ResourceIOArgs(obj.(*ResourceIOArgs)) })
	return nil
}

func SetObjectDefaults_ResourceIOArgs(in *ResourceIOArgs) {
	SetDefaults_ResourceIOArgs(in)
}
